//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMonitry.DataDbc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monotring
    {
        public int Id { get; set; }
        public string Server_Name { get; set; }
        public Nullable<System.DateTime> Software { get; set; }
        public Nullable<System.DateTime> Software1 { get; set; }
        public Nullable<System.DateTime> Software2 { get; set; }
        public Nullable<System.DateTime> Software3 { get; set; }
        public Nullable<System.DateTime> Software4 { get; set; }
        public Nullable<System.DateTime> Software5 { get; set; }
        public Nullable<System.DateTime> Software6 { get; set; }
        public Nullable<System.DateTime> Software7 { get; set; }
        public Nullable<System.DateTime> Software8 { get; set; }
        public Nullable<System.DateTime> Software9 { get; set; }
    }
}
